apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fintrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config
      containers:
        - name: frontend
          image: martinaivanovska04/fintrack-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
